version: '3.9'

services:
  mysql:
    image: mariadb:latest
    container_name: acme_mariadb
    networks:
      - infra_network
    ports:
      - "23306:3306"
    volumes:
      - ./mariadb/acme-script.sql:/docker-entrypoint-initdb.d/acme-script.sql
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: acmedb
      MARIADB_USER: acmeusr
      MARIADB_PASSWORD: acmeusr
      MARIADB_ALLOW_EMPTY_PASSWORD: ssa
      MARIADB_RANDOM_ROOT_PASSWORD: ssa
      LANG: C.UTF-8
    restart: always
    command: ["mysqld","--character-set-server=utf8","--collation-server=utf8_unicode_ci"]



networks:
  infra_network:
    driver: bridge